### ISSUE TITLE
DifferentialEquations failed to precompile [BUG]

### ISSUE THREAD

**Issue by Ezequiel92** [fonsp/pluto-on-binder#10]
Given the [disscusions](https://github.com/fonsp/PlutoUtils.jl/issues/4) in [PlutoUtils.jl](https://github.com/fonsp/PlutoUtils.jl) I don't know how relevant this is, but I tried using [pluto-on-binder](http://pluto-on-binder.glitch.me/) to add a Binder button to a test repo with a Pluto notebook. It works just fine, but the code 

```julia
begin
	
	# We set up a new environment for this notebook
	import Pkg
	Pkg.activate(mktempdir())
	
	
	# This is how you add a package:
	Pkg.add("Plots")
	Pkg.add("DifferentialEquations")
	
	using DifferentialEquations
	using Plots
	
end
```

produces an error (clearly DifferentialEquations.jl is breaking something):

```
Failed to precompile DifferentialEquations [0c46a032-eb83-5123-abaf-570d42b7fbaa] to /srv/julia/pkg/compiled/v1.5/DifferentialEquations/UQdwS_AZyCc.ji.

    error(::String)@error.jl:33
    compilecache(::Base.PkgId, ::String)@loading.jl:1305
    _require(::Base.PkgId)@loading.jl:1030
    require(::Base.PkgId)@loading.jl:928
    require(::Module, ::Symbol)@loading.jl:923
    top-level scope@Local: 12
```

Everything else worked, the testing repo is [test_pluto_notebook](https://github.com/Ezequiel92/test_pluto_notebook) where the binder button should reproduce the error. I will probably keep it up until this works or the whole thing is deprecated.

**Comment by fonsp** [comment]
Can you run the same code in https://github.com/binder-examples/julia-python ? This error is probably out of my control

**Comment by Ezequiel92** [comment]
For what I see, apart from the magic mixing Python and Julia, the only thing different is that it uses a REQUIRE file and jupyter notebooks. if I understand correctly, the modern version would be a Manifest and Project files. That works for me, I tried it already [here](https://github.com/Ezequiel92/test_jupyer_notebook). I wanted to replicate that with Pluto notebooks, that why I tried this repo. 

I tried using the Manifest and Project files and just adding the packages in the Pluto notebook, instead of Pkg.add(). But I get 

```julia 
ArgumentError: Package DifferentialEquations not found in current path: 
- Run `import Pkg; Pkg.add("DifferentialEquations")` to install the DifferentialEquations package. 

    require(::Module, ::Symbol)@loading.jl:893 
    top-level scope@Local: 1 
``` 

I imagine is simply because it is running of this repo, which does not have any packages, and that is why you made your example portable, with Pkg.activate(mktempdir()) and Pkg.add(). But that just my, very non-technical, interpretation. 

I think I will stay with the jupyter notebooks for now. Feel free to close this issue, if there is nothing else to add.

**Comment by fonsp** [comment]
Hm... the goal of this repo is to give a "Pluto demo" that I can put on the readme. It was not meant to be forked and used by others, it does not handle Project.tomls correctly, it is optimized for the wrong things, etc etc. Right now I don't have instructions ready for how you can add pluto and binder to your own repository, but I will write them soon. You should try again then! 

Right now this is too difficult for me to debug, (and not even intended to work).

I will add a warning to the readme!

**Comment by fonsp** [comment]
That being said, my guess is that [this](https://github.com/fonsp/pluto-on-binder/issues/10#issue-781450755) was unrelated to Pluto, but because of Pluto's design you won't be able to read the error messages. [this](https://github.com/fonsp/pluto-on-binder/issues/10#issuecomment-756753221) was because the package environment was not activated.

**Comment by Ezequiel92** [comment]
> Right now I don't have instructions ready for how you can add pluto and binder to your own repository, but I will write them soon. You should try again then!

Ok, I probably will. Thank you for your work.
