### ISSUE TITLE
Failed to precompile Plots on opening notebook on binder

### ISSUE THREAD

**Issue by karthink** [fonsp/pluto-on-binder#13]
I used [http://pluto-on-binder.glitch.me/](http://pluto-on-binder.glitch.me/) to generate a link to a Pluto notebook, but it failed to run/initialize with this error:

```
Distributed.ProcessExitedException(2)
```

The code that generated this error is:

```julia
begin
	using Pkg
	Pkg.activate(mktempdir())
	Pkg.add([Pkg.PackageSpec(name="PlutoUI",version="0.7"),
		 Pkg.PackageSpec(name="Plots"),])
	using PlutoUI, Plots
end
```

The full notebook is [here](https://github.com/karthink/me169/blob/master/2021-04-07.jl). Am I doing something wrong?

----
EDIT: I changed this block into two blocks:

```julia
begin
	using Pkg
	Pkg.activate(mktempdir())
end
```
This block ran without error.

```julia
begin
	Pkg.add("PlutoUI")
	Pkg.add("Plots")
	using PlutoUI, Plots
end
```
This block now failed with the following error:

```julia
Failed to precompile Plots [91a5bcdd-55d7-5caf-9e0b-520d859cae80] to /srv/julia/pkg/compiled/v1.5/Plots/ld3vC_L1MAE.ji.

error(::String)@error.jl:33
compilecache(::Base.PkgId, ::String)@loading.jl:1305
_require(::Base.PkgId)@loading.jl:1030
require(::Base.PkgId)@loading.jl:928
require(::Module, ::Symbol)@loading.jl:923
top-level scope@Local: 4
```

**Comment by fonsp** [comment]
~I just ran it again with the updated binder (Julia 1.6.0, Pluto 0.14.1, running on gke2) and I get an error that the registry is corrupted... [image](https://user-images.githubusercontent.com/6933510/114587334-da2e8f80-9c85-11eb-9886-eb3830f6adfb.png)~

EDIT: it looks like I accidentally opened the notebook twice on the same binder, the Pkg corruption was because of https://github.com/JuliaLang/Pkg.jl/issues/2219

After restarting, I get the same error.

**Comment by karthink** [comment]
I retried it today and it worked fine! (It appears to be running on Julia 1.6.0.)

I need to share this notebook with a class of students so I want to be sure it runs without errors every time. I'll close this for now. Can I reopen it if it fails again?

**Comment by fonsp** [comment]
I tried it today and it failed, so let's not close this yet. Unfortunately this means that the system is not entirely stable.

Binder has "mood swings", and the behavior often depends on your location (which binder provider will you connect to? GKE, turing, etc.) and the time of day (how busy are they?).
