### ISSUE TITLE
pluto-on-binder.glitch.me not working with Safari

### ISSUE THREAD

**Issue by mgiugliano** [fonsp/pluto-on-binder#14]
Under macOs (version 11.6 (20G165)), Safari (Version 15.0 (16612.1.29.41.4, 16612)) does not allow navigating to pluto-on-binder.glitch.me, despite stopping any ad blocker (i.e. ADGUARD).

Instead it works fine with Chrome, even with Ad Blocker on.

**Comment by fonsp** [comment]
It seems to work fine, maybe you can make a screen recording demonstrating your problem?

<img width="906" alt="Schermafbeelding 2021-11-02 om 09 49 49" src="https://user-images.githubusercontent.com/6933510/139814907-7c7903fe-f1f4-4282-8779-f2cb6335a053.png">

**Comment by mgiugliano** [comment]
Thank you for your time and for Pluto.jl, by the way. 

Here is a quick (gif) screen capture: https://www.dropbox.com/s/njt9048xjgh2kc9/ScreenCap_4_Fons.gif?dl=0

**Comment by fonsp** [comment]
I can't reproduce, probably a problem with glitch.com, maybe you can send them an email 🤷
