### ISSUE TITLE
"Package Plots not found in current path"

### ISSUE THREAD

**Issue by mgiugliano** [fonsp/pluto-on-binder#15]
Despite I see in setup.py the line
```
os.system('julia -e "import Pkg; Pkg.add([\\"DataFrames\\", \\"CSV\\", \\"Plots\\"]); Pkg.precompile()"')
```

when I launch a Pluto notebook on Binder, "Plots" is not found and requires (several minutes) to be installed after clicking on the "cloud icon" next to the 'using Plots' line.

**Comment by fonsp** [comment]
Don't pay too much attention to that line, it's just to populate the global cache, which might not always work

See
https://pkgdocs.julialang.org/v1/
https://github.com/fonsp/Pluto.jl/wiki/%F0%9F%8E%81-Package-management#package-installations-are-shared-between-environments
