### ISSUE TITLE
Pkg registry issues with Pluto on Binder

### ISSUE THREAD

**Issue by thompsonmj** [fonsp/pluto-on-binder#18]
Not sure where this issue belongs, but trying to track it down.

I am trying to use Pluto on Binder to load Manifest and Project files from an online repository.

When I download, activate, and instantiate these files, I get the error:
`expected package QOI [4b34888f] to be registered`

See this [Discourse post](https://discourse.julialang.org/t/pluto-on-binder-use-a-repo-environment-rather-than-pluto-managed-environment/75311/4?u=thompsonmj) for more details.

Not sure if this is an issue with [QOi itself,](https://github.com/KristofferC/QOI.jl/issues/10) Pluto on Binder, or something else?

**Comment by thompsonmj** [comment]
Also, maybe I'm missing something, but shouldn't the [built-in Pluto package manager](https://github.com/fonsp/Pluto.jl/wiki/%F0%9F%8E%81-Package-management) be especially practical when using a Pluto notebook on Binder? 

The default example notebook says, "To get packages inside binder - use `Pkg`!" which obviously turns off the built-in manager. Why can't Binder handle a cell of `using` statements and handle these with the Pluto flavor of Pkg?

**Comment by fonsp** [comment]
The website and example notebook were outdated! https://discourse.julialang.org/t/pluto-on-binder-use-a-repo-environment-rather-than-pluto-managed-environment/75311/7?u=fonsp
