### ISSUE TITLE
File is not a Pluto.jl notebook error

### ISSUE THREAD

**Issue by junglegobs** [fonsp/pluto-on-binder#19]
I have a [Pluto notebook here](https://gist.github.com/junglegobs/18d9f69bec8cd7f43a0da2896f0b31a4) which creates [the following binder link](https://binder.plutojl.org/v0.17.1/open?url=https%253A%252F%252Fgist.github.com%252Fjunglegobs).

It is definitely a Pluto notebook, so I don't understand where the error comes from. Is the version of Pluto too old/new?

**Comment by fonsp** [comment]
It looks like you did not copy the full URL from https://pluto-on-binder.glitch.me/ , only the first part. Be sure to right click the URL, and then "Copy URL to clipboard". Hope this helps!
