### ISSUE TITLE
doesn't work

### ISSUE THREAD

**Issue by Moelf** [fonsp/pluto-on-binder#20]
try the example notebook link:

https://mybinder.org/v2/gh/fonsp/pluto-on-binder/v0.19.12?urlpath=pluto/open?url=https%253A%252F%252Fgist.githubusercontent.com%252Ffonsp%252Fd88b3adc8c958dce780cf7c4df8fa437%252Fraw%252F65d760ccb3da5d8be6307b85e40d94a2896ed7b6%252Fturtles.jl

**Comment by fonsp** [comment]
It works for me, what problem are you having? Could you make a video recording or some screenshots?

**Comment by Moelf** [comment]
there seems to be intermediate network issue for the container to build, now it works for me as well.

**Comment by fonsp** [comment]
Hmm... Thanks for the report anyway, if it happens again, make a copy of the build logs and let me know!
