### ISSUE TITLE
Why is this link broken hlep

### ISSUE THREAD

**Issue by fonsp** [fonsp/pluto-on-binder#4]
Notebook:

https://github.com/fonsp/disorganised-mess/blob/master/language%20detection.jl

Direct binder link:

https://mybinder.org/v2/gh/fonsp/pluto-on-binder/master?urlpath=pluto/open?url=https%3A%2F%2Fgist.githubusercontent.com%2Ffonsp%2Fd88b3adc8c958dce780cf7c4df8fa437%2Fraw%2F2a8a5bdc6d8b1bcb4462006f62ead2f52fec17bf%2Fturtles.jl

is broken :(

But if you open the binder to the main menu, and paste the notebook link the blue box, it works.

![image](https://user-images.githubusercontent.com/6933510/93450646-7f42de80-f8d6-11ea-8d74-553e4a0f720c.png)

Maybe the URL needs to be encoded twice?

**Comment by fonsp** [comment]
@dralletje

**Comment by dralletje** [comment]
@fonsp close this thank you
